agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = "agents"

urlpatterns = [
    path('', AgentListView.as_view(), name="agents"),
    path('create/', AgentCreateView.as_view(), name='agents_create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agents_detail'),
    path('<int:pk>/update', AgentUpdateView.as_view(), name='agents_update'),
    path('<int:pk>/delete', AgentDeleteView.as_view(), name='agents_delete'),
]

app/urls.py
from django.urls import path
from .views import home_page, app_students, app_update, app_delete, app_students_update, app_student_delete, students_page, app_create, app_student_detail, ManagementListView, AssignAgentView

app_name = "apps"
urlpatterns = [
    path('', home_page,  name='home'),
    path('<int:pk>/', ManagementListView.as_view(), name='detail'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(),name='assign_agent'),
    path('<int:pk>/update/', app_update, name='update'),
    path('<int:pk>/delete/', app_delete, name='delete'),
    path('create/', app_create, name='create'),
    path('student1/', students_page, name='stu'),
    path('student/', app_students, name='students'),
    path('students/<int:pk>', app_student_detail, name='student_detail'),
    path('students/<int:pk>/update', app_students_update, name='student_update'),
    path('students/<int:pk>/delete', app_student_delete, name='student_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import landing_page, SignupView
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page),
    path('app/', include('app.urls', namespace='apps')),
    path('signup/', SignupView.as_view(), name="signup"),
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('agents/', include('agents.urls', namespace='agents')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
# from app.models import UserAgent
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )

agents/views.py
import random
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
from app.models import UserAgent
from .forms import AgentModelForm
from django.core.mail import send_mail
from .mixins import OrganisorAndLoginRequiredMixin

class AgentListView(OrganisorAndLoginRequiredMixin, ListView):
    template_name = "agents/agents_list.html"
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return UserAgent.objects.filter(organization=organization)
    
class AgentCreateView(OrganisorAndLoginRequiredMixin, CreateView):
    template_name = 'agents/agents_create.html'
    form_class = AgentModelForm
    
    def get_success_url(self):
        return reverse("agents:agents")
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f"{random.randint(0, 100000)}")
        user.save()
        UserAgent.objects.create(
            user=user,
            organization = self.request.user.userprofile,
        )
        send_mail(
            subject = "Agent Smith has been created",
            message = "You have been created as an agent for the matrix.",
            from_email="admin@test.com",
            recipient_list = [user.email]
        )
        return super(AgentCreateView, self).form_valid(form)
    
class AgentDetailView(OrganisorAndLoginRequiredMixin, DetailView):
    template_name = 'agents/agents_detail.html'
    context_object_name = 'agent'
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return UserAgent.objects.filter(organization=organization)
    
    
class AgentUpdateView(OrganisorAndLoginRequiredMixin, UpdateView):
    template_name = 'agents/agents_update.html'
    context_object_name = 'agent'
    form_class = AgentModelForm
    
    def get_queryset(self):
        return UserAgent.objects.all()
    
    def get_success_url(self):
        return reverse("agents:agents")
    
class AgentDeleteView(OrganisorAndLoginRequiredMixin, DeleteView):
    template_name = 'agents/agents_delete.html'
    context_object_name = 'agent'
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return UserAgent.objects.filter(organization=organization)
    
    def get_success_url(self):
        return reverse("agents:agents")

agents/templates/agents/agents_create.html
{% extends "base.html" %}

{% block content %}
<a href='{% url 'agents:agents' %}'>Go back to Agents</a>

<h1>Create New Agent</h1>
    <form method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <input type='submit'/>
    </form>
{% endblock content %}

agents/templates/agents/agents_delete.html
{% extends "base.html" %}

{% block content %}
<a href='{% url 'agents:agents' %}'>Go back to Agents</a>

<h1>Do you want to delete this agent?</h1>
    <form method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <input type='submit'/>
    </form>
{% endblock content %}

agents/templates/agents/agents_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">This Space is for: {{agent.user.username}}</h1>
        <div class="flex mb-4">
          <a href='{% url 'agents:agents_detail' agent.pk %}'class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
          <a href='/' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Home</a>
          <a href='{% url 'agents:agents_update' agent.pk %}' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>

        <div class="flex">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href='#'>Delete</a></button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

{% endblock content %}

agents/templates/agents/agents_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
  <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-300">
    <div>
        <h1 class="text-4xl text-gray-800">Here are the agents</h1>
    </div>
    <div>
        <a class="text-gray-400 hover:text-blue-300" href='{%url 'agents:agents_create'%}' class="mr-6 hover:text-gray-900 font-bold text-xl left-10">Create New Agent</a>
    </div>
  </div>
    <div class="flex flex-wrap -m-4">
    {% for agent in object_list %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3"> {{ agent.user.username}}</h2>
            <p class="leading-relaxed text-base">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
            <a href='{% url 'agents:agents_detail' agent.pk %}' class="mt-3 text-indigo-500 inline-flex items-center">Learn More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</section>

{% endblock content %}

agents/templates/agents/agents_update.html
{% extends "base.html" %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">This Space is for: {{agent.user.username}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:agents_detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
          <a href='/' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Home</a>
          <a href='{% url 'agents:agents_update' agent.pk %}' class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
        </div>
            <form method='post'>
                {% csrf_token %}
                {{form.as_p}}
                <input type='submit'/>
            </form>
        <div class="flex">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href='{%url 'agents:agents_delete' agent.pk%}'>Delete</a></button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

    
{% endblock content %}