agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = "agents"

urlpatterns = [
    path('', AgentListView.as_view(), name="agents"),
    path('create/', AgentCreateView.as_view(), name='agents_create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agents_detail'),
    path('<int:pk>/update', AgentUpdateView.as_view(), name='agents_update'),
    path('<int:pk>/delete', AgentDeleteView.as_view(), name='agents_delete'),
]

app/urls.py
from django.urls import path
from .views import home_page, app_students, app_update, app_delete, app_students_update, app_student_delete, students_page, app_create, app_student_detail, ManagementListView, AssignAgentView

app_name = "apps"
urlpatterns = [
    path('', home_page,  name='home'),
    path('<int:pk>/', ManagementListView.as_view(), name='detail'),
    path('<int:pk>/assign-agent/', AssignAgentView.as_view(),name='assign_agent'),
    path('<int:pk>/update/', app_update, name='update'),
    path('<int:pk>/delete/', app_delete, name='delete'),
    path('create/', app_create, name='create'),
    path('student1/', students_page, name='stu'),
    path('student/', app_students, name='students'),
    path('students/<int:pk>', app_student_detail, name='student_detail'),
    path('students/<int:pk>/update', app_students_update, name='student_update'),
    path('students/<int:pk>/delete', app_student_delete, name='student_delete'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import landing_page, SignupView
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page),
    path('app/', include('app.urls', namespace='apps')),
    path('signup/', SignupView.as_view(), name="signup"),
    path('reset-password/', PasswordResetView.as_view(), name="reset-password"),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('agents/', include('agents.urls', namespace='agents')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/app_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
<div class="text-sm mb-3 border-b-2 py-2 text-gray-500">
    <a href='/'>Go back to home</a>
</div>
    <div class="text-lg mb-3  py-2 text-gray-800">
        <h1>Create a new management</h1>
    </div>
    <form method='post'>
        {% csrf_token %}
        {{form|crispy}}
        <div class="py-5 border-blue-500 mt-5 hover:bg-blue-500 rounded-md text-center bg-indigo-500 text-white">
        <input type='submit'/>
        </div>
    </form>
</div>    
{% endblock content %}

app/templates/app_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">MANAGEMENT</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">This Space is for: {{students.name}}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
          <a href='/' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Home</a>
          <a href='{% url 'apps:update' user.pk %}' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Management</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Email</span>
          <span class="ml-auto text-gray-900">{{students.email}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Profession</span>
          <span class="ml-auto text-gray-900">{{students.profession}}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Date of Employment</span>
          <span class="ml-auto text-gray-900">{{students.date_of_employment}}</span>
        </div>
        <div class="flex">
          <button class="flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a>Update</a></button>
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href='{% url 'apps:delete' user.pk %}'>Delete</a></button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

{% endblock content %}

app/templates/app_student_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">STUDENTS</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">This Space is for: {{students.name}}</h1>
        <div class="flex mb-4">
          <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
          <a href='/' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Home</a>
          <a href='{% url 'apps:student_update' user.pk %}' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
        </div>
        <p class="leading-relaxed mb-4">{{students.description}}</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Year Level</span>
          <span class="ml-auto text-gray-900">{{students.year_level}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">ACADEMIC LEVEL</span>
          <span class="ml-auto text-gray-900">{{students.academic_level}}</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Lecturers</span>
          <span class="ml-auto text-gray-900">{{students.Lecturers}}</span>
        </div>
        <div class="flex">
          <button class="flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href='{% url 'apps:student_update' user.pk %}'>Update</a></button>
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href='{% url 'apps:student_delete' user.pk %}'>Delete</a></button>
        </div>
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

{% endblock content %}

app/templates/app_students.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}


<div class="max-w-lg mx-auto">
<div class="text-sm mb-3 border-b-2 py-2 text-gray-500">
    <a href='/'>Go back to home</a>
</div>
    <div class="text-lg mb-3 py-2 text-gray-800">
    <h1>Create a new Student</h1>
    </div>
    <form method='post'>
        {% csrf_token %}
        {{form|crispy}}
        <div class="py-5 border-blue-500 mt-5 hover:bg-blue-500 rounded-md text-center bg-indigo-500 text-white">
        <input type='submit'/>
        </div>
    </form>
</div>
{% endblock content %}

app/templates/app_students_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">STUDENTS</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">This Space is for: {{students.name}}</h1>
        <div class="flex mb-4">
          <a href='{% url 'apps:student_detail' user.pk %}' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
          <a href='/' class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Home</a>
          <a href='{% url 'apps:student_update' user.pk %}' class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
        </div>
            <form method='post'>
                {% csrf_token %}
                {{form|crispy}}
                <div class="flex">
                <input class="flex mr-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded" type='submit'/>
                </div>
            </form>
        <div class="mt-5 py-5 border-t border-gray-200">
          <button class=" text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"><a href='{% url 'apps:student_delete' user.pk %}'>Delete</a></button>
        </div>
      </div>
    </div>
  </div>
</section>

<h1>Update Student</h1>
    
{% endblock content %}

app/templates/app_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}


<div class="max-w-lg mx-auto">
<div class="text-sm mb-3 border-b-2 py-2 text-gray-500">
    <a href='/'>Go back to home</a>
</div>
<div class="text-lg mb-3 py-2 text-gray-800">
    <h1>Update a new management</h1>
</div>
    <form method='post'>
        {% csrf_token %}
        {{form|crispy}}
        <div class="py-5 border-blue-500 mt-5 hover:bg-blue-500 rounded-md text-center bg-indigo-500 text-white">
        <input type='submit'/>
        </div>
    </form>
</div>    
{% endblock content %}

app/templates/assign_agent.html
{% extends "base.html" %}

{% block content %}
<a href='/'>Go back to home</a>

<h1>Assign agent to lead</h1>
    <form method='post'>
        {% csrf_token %}
        {{form.as_p}}
        <input type='submit'/>
    </form>
{% endblock content %}

app/templates/base.html
{%load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp"></script>
        <link rel="stylesheet" href="{% static 'css/style.css'%}">
    </head>
    <body>
        {%include 'navbar.html'%}
        {% block content %}
        
        {% endblock content %}
    </body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="text-center text-lg font-normal">


{% comment %} <a href='/create' class=" font-bold">Add a new management staff</a>
<br />
<a href='/student'class=" font-bold ">Add a new student</a>
<hr /> {% endcomment %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
  <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-300">
    <div>
        <h1 class="text-4xl text-gray-800">Management</h1>
    </div>
    <div>
        <a class="text-gray-400 hover:text-blue-300" href='{%url 'apps:create'%}' class="mr-6 hover:text-gray-900 font-bold text-xl left-10">Create New Management</a>
    </div>
  </div>
    <div class="flex flex-wrap -m-4">
    {% for user in user %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{user.name}}</h2>
            <p class="leading-relaxed text-base">Profession : {{user.profession}}</p>
            <a href='{% url 'apps:detail' user.pk%}' class="mt-3 text-indigo-500 inline-flex items-center">Learn More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</section>

 {% comment %} <ul>
{% for user in user %}
    <li>
    <a href='{% url 'apps:detail' user.pk%}'>{{user.name}} : {{user.email}}</a>
    </li>
    {% endfor %}
</ul> {% endcomment %}


{% endblock content %}

app/templates/landing.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Welcome to
        <br class="hidden lg:inline-block">Telulah
      </h1>
      <p class="mb-8 leading-relaxed">The School where we raise next generations of leaders to build the next big things. Apart from normal schooling activities, we also teach Soft skills like Communication,Leadership and Teamwork,. We also teach technical skills such as Robotics, Data Analytics, Machine Learning, Software Development and Cybersecurity as well as others.</p>
      <div class="flex justify-center">
        <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Learn More</button>
        <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Login</button>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
      <img class="object-cover object-center rounded" src="{% static 'images/undraw_educator_re_ju47_1.png' %}">
    </div>
  </div>
</section>
<section class="text-gray-600 body-font relative">
  <div class="container px-5 py-24 mx-auto flex sm:flex-nowrap flex-wrap">
    <div class="lg:w-2/3 md:w-1/2 bg-gray-300 rounded-lg overflow-hidden sm:mr-10 p-10 flex items-end justify-start relative">
      <iframe width="100%" height="100%" class="absolute inset-0" frameborder="0" title="map" marginheight="0" marginwidth="0" scrolling="no" src="https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;q=%C4%B0zmir+(My%20Business%20Name)&amp;ie=UTF8&amp;t=&amp;z=14&amp;iwloc=B&amp;output=embed" style="filter: grayscale(1) contrast(1.2) opacity(0.4);"></iframe>
      <div class="bg-white relative flex flex-wrap py-6 rounded shadow-md">
        <div class="lg:w-1/2 px-6">
          <h2 class="title-font font-semibold text-gray-900 tracking-widest text-xs">ADDRESS</h2>
          <p class="mt-1">2, Olayinka Williams close, Oke-Ira Nla, Ajah, Lagos.</p>
        </div>
        <div class="lg:w-1/2 px-6 mt-4 lg:mt-0">
          <h2 class="title-font font-semibold text-gray-900 tracking-widest text-xs">EMAIL</h2>
          <a class="text-indigo-500 leading-relaxed">olasubomiwilliams1@gmail.com</a>
          <h2 class="title-font font-semibold text-gray-900 tracking-widest text-xs mt-4">PHONE</h2>
          <p class="leading-relaxed">+234-705-946-4235</p>
        </div>
      </div>
    </div>
    <div class="lg:w-1/3 md:w-1/2 bg-white flex flex-col md:ml-auto w-full md:py-8 mt-8 md:mt-0">
      <h2 class="text-gray-900 text-lg mb-1 font-medium title-font">Feedback</h2>
      <p class="leading-relaxed mb-5 text-gray-600">Contact me while I am still avaliable</p>
      <div class="relative mb-4">
        <label for="name" class="leading-7 text-sm text-gray-600">Name</label>
        <input type="text" id="name" name="name" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <div class="relative mb-4">
        <label for="email" class="leading-7 text-sm text-gray-600">Email</label>
        <input type="email" id="email" name="email" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 text-base outline-none text-gray-700 py-1 px-3 leading-8 transition-colors duration-200 ease-in-out">
      </div>
      <div class="relative mb-4">
        <label for="message" class="leading-7 text-sm text-gray-600">Message</label>
        <textarea id="message" name="message" class="w-full bg-white rounded border border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out" data-gramm="false" wt-ignore-input="true"></textarea>
      </div>
      <button class="text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Submit</button>
      <p class="text-xs text-gray-500 mt-3">My name is Olasubomi Williams.</p>
    </div>
  </div>
</section>

{% endblock content %}

app/templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a href='/'class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Telulah</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <a href='{% url 'apps:home' %}' class="mr-5 hover:text-gray-900">Mangement list</a>
      {% if not request.user.is_authenticated %}
      <a href="{% url 'signup'%}" class="mr-5 hover:text-gray-900">Signup</a>
      {%else%}
            <a href='{%url 'apps:create'%}' class="mr-5 hover:text-gray-900">Create</a>
            <a href='{% url 'apps:stu' %}' class="mr-5 hover:text-gray-900">Student</a>
            {% if request.user.is_organisor %}
            <a href='{% url 'agents:agents' %}' class="mr-5 hover:text-gray-900">Agents</a>
            {% endif %}
      {% endif %}
    </nav>
    {% if request.user.is_authenticated %}
       logged in: {{request.user.username}}
      <button class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0"><a href="{% url 'logout'%}">Logout</a>
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </button>
    {%else%}
    <button class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0"><a href="{% url 'login' %}">Login</a>
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </button>
    {% endif %}
  </div>
</header>

app/templates/students.html
{% extends "base.html" %}
{% block content %}
<div class="text-center text-lg font-normal">


{% comment %} <a href='/create' class=" font-bold">Add a new management staff</a>
<br />
<a href='/student'class=" font-bold ">Add a new student</a>
<hr /> {% endcomment %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
  <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-300">
    <div>
        <h1 class="text-4xl text-gray-800">Students</h1>
    </div>
    <div>
        <a class="text-gray-400 hover:text-blue-300" href='{%url 'apps:students'%}' class="mr-6 hover:text-gray-900 font-bold text-xl left-10">Create New Student</a>
    </div>
  </div>
    <div class="flex flex-wrap -m-4">
    {% for user in user %}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{user.name}}</h2>
            <p class="leading-relaxed text-base">Academic Level : {{user.academic_level}}</p>
            <a href='{% url 'apps:student_detail' user.pk%}' class="mt-3 text-indigo-500 inline-flex items-center">Learn More
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</section>



{% endblock content %}